### ISSUE TITLE
Can't find the module in conda list after install.

### ISSUE THREAD

**Issue by Flawintheory** [dfm/python-finufft#1]
I use an Arch system. When I firstly install the setup.py I got the error "can't find the fftw3", but I have installed it before the installation, then I edit your code in build.py, and add my directory of fftw3 (/usr/include) to the dirs. And it works, but after I finish the installation, I can't import the module, of course the py.test can't work. And I can't find the finufft module in my conda list neither.

**Comment by dfm** [comment]
The command to use for installation is

python setup.py build_ext -I/path/to/fftw install

If this runs without error, you'll be able to import and run py.test. This
install has nothing to do with conda so you'll never see it there.

**Comment by Flawintheory** [comment]
It woks, and I found that install libgcc is also needed. Thank you so much!

**Comment by dfm** [comment]
Great! Glad to hear it.
