### ISSUE TITLE
NuFFT on 2D arrays?

### ISSUE THREAD

**Issue by kaanaksit** [dfm/python-finufft#2]
Thank you for putting this library together! Is there any example on how to apply NuFFT on 2D arrays using `python-finufft`? I am bit lost with this [example](https://github.com/dfm/python-finufft/blob/main/tests/test_2d.py#L48) provided in your test folder.

Does one use `flatten` to work with 2D arrays?
```python
 result = finufft.nufft2d3(fx.flatten(), fy.flatten(), image.flatten(), fx.flatten(),fy.flatten(),isign=sign)
```

**Comment by dfm** [comment]
I'd recommend using `finufft` directly instead of this package since it now has built in Python support and better documentation 😀: https://finufft.readthedocs.io/en/latest/python.html

Give that a shot and see how it goes!
